export const CLOUD_OPTIONS: Record<string, any> = {
  animTiming: 'Smooth',
  reverse: true,
  depth: 1,
  wheelZoom: false,
  imageScale: 2,
  activeCursor: 'default',
  tooltip: 'native',
  initial: [0.1, -0.1],
  clickToFront: 500,
  tooltipDelay: 0,
  outlineColour: '#0000',
  maxSpeed: 0.03,
  minSpeed: 0.01,
  dragControl: true,
  decel: 0.98,
  pinchZoom: false,
  freezeActive: true,
  freezeDecel: true,
  textFont: null,
  textColour: null,
};
