import { ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideRouter, withInMemoryScrolling } from '@angular/router';
import { provideClientHydration, withEventReplay } from '@angular/platform-browser';
import { LUCIDE_ICONS, LucideIconProvider } from 'lucide-angular';
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  BookOpen,
  Braces,
  Brain,
  Briefcase,
  Building2,
  Calendar,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronRight,
  Code,
  Code2,
  Coffee,
  Copy,
  Cpu,
  Database,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileJson,
  FileText,
  Folder,
  Github,
  GitBranch,
  Globe,
  GraduationCap,
  Heart,
  Home,
  Info,
  Layers,
  Layout,
  Lightbulb,
  Linkedin,
  Loader2,
  Lock,
  Mail,
  MapPin,
  MessageCircle,
  Monitor,
  Moon,
  Palette,
  RefreshCw,
  Rocket,
  Search,
  Send,
  Server,
  Shield,
  Smartphone,
  Sparkles,
  Star,
  Sun,
  Terminal,
  Trophy,
  User,
  Wifi,
  Wrench,
  X,
  Zap,
} from 'lucide-angular';

import { routes } from './app.routes';

const usedIcons = {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  BookOpen,
  Braces,
  Brain,
  Briefcase,
  Building2,
  Calendar,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronRight,
  Code,
  Code2,
  Coffee,
  Copy,
  Cpu,
  Database,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileJson,
  FileText,
  Folder,
  Github,
  GitBranch,
  Globe,
  GraduationCap,
  Heart,
  Home,
  Info,
  Layers,
  Layout,
  Lightbulb,
  Linkedin,
  Loader2,
  Lock,
  Mail,
  MapPin,
  MessageCircle,
  Monitor,
  Moon,
  Palette,
  RefreshCw,
  Rocket,
  Search,
  Send,
  Server,
  Shield,
  Smartphone,
  Sparkles,
  Star,
  Sun,
  Terminal,
  Trophy,
  User,
  Wifi,
  Wrench,
  X,
  Zap,
};

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes, withInMemoryScrolling({ anchorScrolling: 'disabled', scrollPositionRestoration: 'enabled' })),
    provideClientHydration(withEventReplay()),
    { provide: LUCIDE_ICONS, multi: true, useValue: new LucideIconProvider(usedIcons) }
  ]
};
